<?php

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\user\UserInterface;
use \Drupal\Core\Session\AccountProxyInterface;


/**
 * @param $route_name
 * @param RouteMatchInterface $route_match
 * @return string
 */
function hello_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.hello':
      return '<p>' . t('This............ ') . '</p>';

  }
}

# Planifier une tache
function hello_cron()
{
  \Drupal::messenger()->addMessage(t('Hello CRON'));
}

function hello_user_login(UserInterface $account)
{
  \Drupal::messenger()->addMessage(t('Welcome dear %name!', ['%name' => $account->getAccountName()]

  ));
  $uid = $account->id();

 \Drupal::database()->insert('hello_user_statistics')
 ->fields([
      'time' => REQUEST_TIME,
      'uid' => $uid,
      'action'=>1,
    ])->execute();
}

function hello_user_logout(AccountProxyInterface $account)
{

 $uid = $account->id();

  \Drupal::database()->insert('hello_user_statistics')
    ->fields([
      'time' => REQUEST_TIME,
      'uid' => $uid,
      'action'=>0,
    ])->execute();
}

